/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.DeliveryAgent;

import Business.Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Role.Role;
import javax.swing.JPanel;
import Business.Business.EcoSystem;
import Business.DB4OUtil.DB4OUtil;

import Business.Employee.Employee;
import Business.Employee.EmployeeDirectory;
import Business.Enterprise.Enterprise;
import Business.Organization.DeliveryManOrganization;
import Business.Organization.Organization;
import Business.Organization.StoreReceptionistOrganization;
import Business.Role.DeliveryManRole;


import Business.Role.Role;
import Business.Role.Role.RoleType;
import Business.Role.StoreDistributionPersonnelRole;
import Business.Role.StoreReceptionistRole;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author 加藤鹰
 */
public class CreateDeliveryManJPanel extends javax.swing.JPanel {

    private EcoSystem system;
    private Enterprise enterprise;
    private JPanel dajp;
    private JPanel DeliveryManWorkPanel;
    /**
     * Creates new form CreateDeliveryManJPanel
     */
    public CreateDeliveryManJPanel() {
        initComponents();
    }

    CreateDeliveryManJPanel(EcoSystem system, DeliveryAgentJPanel aThis, JPanel workPanel, Enterprise enterprise) {
        initComponents();
        this.system = system;
        this.dajp = aThis;
        this.DeliveryManWorkPanel =  workPanel;
        this.enterprise = enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitlejLabel1 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        namejLabel4 = new javax.swing.JLabel();
        firstNamejTextField = new javax.swing.JTextField();
        namejLabel5 = new javax.swing.JLabel();
        lastjTextField = new javax.swing.JTextField();
        jLabelphoneNumber4 = new javax.swing.JLabel();
        PhoneNumberjTextField = new javax.swing.JTextField();
        jLabelphoneNumber5 = new javax.swing.JLabel();
        UserNamejTextField = new javax.swing.JTextField();
        AddressjLabel9 = new javax.swing.JLabel();
        passwordJPasswordField = new javax.swing.JPasswordField();

        TitlejLabel1.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        TitlejLabel1.setText("Create DeliveryMan Account");

        cancelButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        btnCreate.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        namejLabel4.setText("FirstName");

        namejLabel5.setText("LastName");

        jLabelphoneNumber4.setText("PhoneNumber");

        PhoneNumberjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberjTextFieldActionPerformed(evt);
            }
        });

        jLabelphoneNumber5.setText("UserName");

        UserNamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNamejTextFieldActionPerformed(evt);
            }
        });

        AddressjLabel9.setText("PassWord");

        passwordJPasswordField.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        passwordJPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordJPasswordFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TitlejLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnCreate)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(namejLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AddressjLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelphoneNumber5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelphoneNumber4))
                                .addComponent(namejLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(72, 72, 72)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lastjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(passwordJPasswordField)
                                    .addComponent(UserNamejTextField)
                                    .addComponent(firstNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PhoneNumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitlejLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namejLabel4)
                    .addComponent(firstNamejTextField))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namejLabel5)
                    .addComponent(lastjTextField))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNumberjTextField)
                    .addComponent(jLabelphoneNumber4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelphoneNumber5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressjLabel9)
                    .addComponent(passwordJPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(cancelButton))
                .addContainerGap(93, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.DeliveryManWorkPanel.remove(this);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
       String firstName = firstNamejTextField.getText();
        String phoneNumber = PhoneNumberjTextField.getText();
        String lastName = lastjTextField.getText();
        String userName = UserNamejTextField.getText();
        String password = String.valueOf(passwordJPasswordField.getPassword());
        if (firstName.trim().equals("") || phoneNumber.trim().equals("") || lastName.trim().equals("") || userName.trim().equals("")
                || password.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Fields cannot be left empty");
            return;
        }
          try{
         long l= Long.parseLong(phoneNumber);
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Incorrect phone number input format!");
            return;
        }
        Boolean used = false;
        for (UserAccount ua : system.getUserAccountDirectory().getUserAccountList()) {
            if (userName.equals(ua.getUsername())) {

                used = true;
                break;
            }

        }
        if (used == false) {
            Label1:
            for (Enterprise en : system.getEnterpriseDirectory().getEnterpriseList()) {

                for (Organization org : en.getOrganizationDirectory().getOrganizationList()) {
                    for (UserAccount ua : org.getUserAccountDirectory().getUserAccountList()) {
                        if (userName.equals(ua.getUsername())) {

                            used = true;
                            break Label1;

                        }

                    }
                }

            }
        }
        if (used == true) {
            JOptionPane.showMessageDialog(this, "UserName has been used", "Warning", JOptionPane.WARNING_MESSAGE);
            return;

        }
         DeliveryManOrganization dmorg = null;
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {

            if (org instanceof DeliveryManOrganization) {
                dmorg = (DeliveryManOrganization) org;
                break;
            }

        }
       Employee e = new Employee();
       e.setFirstName(firstName);
       e.setLastName(lastName);
       e.setPhone(phoneNumber);
  
        dmorg.getUserAccountDirectory().createUserAccount(userName, password, e, new DeliveryManRole());

        JOptionPane.showMessageDialog(null, "DeliveryMan Created");
        DB4OUtil.getInstance().storeSystem(system);
        DeliveryAgentJPanel p = (DeliveryAgentJPanel) dajp;
        p.populateDeliveryMan();
        this.DeliveryManWorkPanel.remove(this);
        CardLayout layout = (CardLayout) this.DeliveryManWorkPanel.getLayout();
        layout.previous(this.DeliveryManWorkPanel);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void PhoneNumberjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberjTextFieldActionPerformed

    private void UserNamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNamejTextFieldActionPerformed

    private void passwordJPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordJPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordJPasswordFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressjLabel9;
    private javax.swing.JTextField PhoneNumberjTextField;
    private javax.swing.JLabel TitlejLabel1;
    private javax.swing.JTextField UserNamejTextField;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField firstNamejTextField;
    private javax.swing.JLabel jLabelphoneNumber4;
    private javax.swing.JLabel jLabelphoneNumber5;
    private javax.swing.JTextField lastjTextField;
    private javax.swing.JLabel namejLabel4;
    private javax.swing.JLabel namejLabel5;
    private javax.swing.JPasswordField passwordJPasswordField;
    // End of variables declaration//GEN-END:variables
}
