/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.DeliveryAgent;

import Business.Business.EcoSystem;
import Business.DB4OUtil.DB4OUtil;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.DriverOrganization;
import Business.Organization.Organization;
import Business.Role.Driver;

import Business.UserAccount.UserAccount;
import javax.swing.JPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author 加藤鹰
 */
public class CreateDriverJPanel extends javax.swing.JPanel {

    private EcoSystem system;
    private Enterprise enterprise;
    private JPanel dajp;
    private JPanel DriverWorkPane;

    /**
     * Creates new form CreateDriverJPanel
     */
    public CreateDriverJPanel() {
        initComponents();
    }

    CreateDriverJPanel(EcoSystem system, DeliveryAgentJPanel aThis, JPanel workPanel, Enterprise enterprise) {
        initComponents();
        this.system = system;
        this.dajp = aThis;
        this.DriverWorkPane = workPanel;
        this.enterprise = enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelphoneNumber4 = new javax.swing.JLabel();
        firstNamejTextField = new javax.swing.JTextField();
        PhoneNumberjTextField = new javax.swing.JTextField();
        UserNamejTextField = new javax.swing.JTextField();
        TitlejLabel1 = new javax.swing.JLabel();
        jLabelphoneNumber5 = new javax.swing.JLabel();
        AddressjLabel9 = new javax.swing.JLabel();
        namejLabel4 = new javax.swing.JLabel();
        cancelButton2 = new javax.swing.JButton();
        passwordJPasswordField = new javax.swing.JPasswordField();
        btnCreate = new javax.swing.JButton();
        namejLabel5 = new javax.swing.JLabel();
        lastjTextField = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(337, 385));

        jLabelphoneNumber4.setText("PhoneNumber");

        PhoneNumberjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberjTextFieldActionPerformed(evt);
            }
        });

        UserNamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNamejTextFieldActionPerformed(evt);
            }
        });

        TitlejLabel1.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        TitlejLabel1.setText("Create Driver Account");

        jLabelphoneNumber5.setText("UserName");

        AddressjLabel9.setText("PassWord");

        namejLabel4.setText("FirstName");

        cancelButton2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cancelButton2.setText("Cancel");
        cancelButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton2ActionPerformed(evt);
            }
        });

        passwordJPasswordField.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        passwordJPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordJPasswordFieldActionPerformed(evt);
            }
        });

        btnCreate.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        namejLabel5.setText("LastName");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(btnCreate)
                .addGap(110, 110, 110)
                .addComponent(cancelButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelphoneNumber4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(206, 206, 206))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namejLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(AddressjLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                .addComponent(jLabelphoneNumber5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordJPasswordField)
                            .addComponent(UserNamejTextField)
                            .addComponent(firstNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PhoneNumberjTextField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(TitlejLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(namejLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(lastjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitlejLabel1)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namejLabel4)
                    .addComponent(firstNamejTextField))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namejLabel5)
                    .addComponent(lastjTextField))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNumberjTextField)
                    .addComponent(jLabelphoneNumber4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelphoneNumber5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressjLabel9)
                    .addComponent(passwordJPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton2)
                    .addComponent(btnCreate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(26, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(26, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PhoneNumberjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberjTextFieldActionPerformed

    private void UserNamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNamejTextFieldActionPerformed

    private void cancelButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton2ActionPerformed
        this.DriverWorkPane.remove(this);
    }//GEN-LAST:event_cancelButton2ActionPerformed

    private void passwordJPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordJPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordJPasswordFieldActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        String firstName = firstNamejTextField.getText();
        String phoneNumber = PhoneNumberjTextField.getText();
        String lastName = lastjTextField.getText();
        String userName = UserNamejTextField.getText();
        String password = String.valueOf(passwordJPasswordField.getPassword());
        if (firstName.trim().equals("") || phoneNumber.trim().equals("") || lastName.trim().equals("") || userName.trim().equals("")
                || password.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Fields cannot be left empty");
            return;
        }
          try{
          long l= Long.parseLong(phoneNumber);
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Incorrect phone number input format!");
            return;
        }
        Boolean used = false;
        for (UserAccount ua : system.getUserAccountDirectory().getUserAccountList()) {
            if (userName.equals(ua.getUsername())) {

                used = true;
                break;
            }

        }
        if (used == false) {
            Label1:
            for (Enterprise en : system.getEnterpriseDirectory().getEnterpriseList()) {

                for (Organization org : en.getOrganizationDirectory().getOrganizationList()) {
                    for (UserAccount ua : org.getUserAccountDirectory().getUserAccountList()) {
                        if (userName.equals(ua.getUsername())) {

                            used = true;
                            break Label1;

                        }

                    }
                }

            }
        }
        if (used == true) {
            JOptionPane.showMessageDialog(this, "UserName has been used", "Warning", JOptionPane.WARNING_MESSAGE);
            return;

        }

        DriverOrganization drorg = null;
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {

            if (org instanceof DriverOrganization) {
                drorg = (DriverOrganization) org;
                break;
            }

        }
        Employee e = new Employee();
        e.setFirstName(firstName);
        e.setLastName(lastName);
        e.setPhone(phoneNumber);

        drorg.getUserAccountDirectory().createUserAccount(userName, password, e, new Driver());

        JOptionPane.showMessageDialog(null, "Driver Created");
        DB4OUtil.getInstance().storeSystem(system);
        DeliveryAgentJPanel p = (DeliveryAgentJPanel) dajp;
        p.populateDriver();

        this.DriverWorkPane.remove(this);
        CardLayout layout = (CardLayout) this.DriverWorkPane.getLayout();
        layout.previous(this.DriverWorkPane);
    }//GEN-LAST:event_btnCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressjLabel9;
    private javax.swing.JTextField PhoneNumberjTextField;
    private javax.swing.JLabel TitlejLabel1;
    private javax.swing.JTextField UserNamejTextField;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton cancelButton2;
    private javax.swing.JTextField firstNamejTextField;
    private javax.swing.JLabel jLabelphoneNumber4;
    private javax.swing.JLabel jLabelphoneNumber5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastjTextField;
    private javax.swing.JLabel namejLabel4;
    private javax.swing.JLabel namejLabel5;
    private javax.swing.JPasswordField passwordJPasswordField;
    // End of variables declaration//GEN-END:variables
}
