/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Business.Business.EcoSystem;
import Business.DB4OUtil.DB4OUtil;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author tzm
 */
public class RegisterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterJPanel
     */
    private EcoSystem system;
    private JPanel loginJPanel;



    /**
     * Creates new form LoginJPanel
     */
    public RegisterJPanel(EcoSystem system, JPanel loginJPanel) {
        initComponents();
        this.system = system;
        this.loginJPanel = loginJPanel;
      
        this.setSize(300, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        storeJButton = new javax.swing.JButton();
        deliveryAgentJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        customerJButton = new javax.swing.JButton();

        storeJButton.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        storeJButton.setText("Registering As Stores");
        storeJButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        storeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeJButtonActionPerformed(evt);
            }
        });

        deliveryAgentJButton.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        deliveryAgentJButton.setText("Registering As DeliveryAgents");
        deliveryAgentJButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        deliveryAgentJButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        deliveryAgentJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveryAgentJButtonActionPerformed(evt);
            }
        });

        backJButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        backJButton.setText("Back");
        backJButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        backJButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        customerJButton.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        customerJButton.setText("Registering As Customers");
        customerJButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        customerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deliveryAgentJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(storeJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(customerJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backJButton)
                .addGap(72, 72, 72)
                .addComponent(customerJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(storeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(deliveryAgentJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void storeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeJButtonActionPerformed
        RgtSJPanel rsj = new RgtSJPanel(system, loginJPanel);
        loginJPanel.add(rsj);
        CardLayout layout = (CardLayout) loginJPanel.getLayout();
        layout.next(loginJPanel);
    }//GEN-LAST:event_storeJButtonActionPerformed

    private void deliveryAgentJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveryAgentJButtonActionPerformed
        RgtDJPanel rsd = new RgtDJPanel(system, loginJPanel);
        loginJPanel.add(rsd);
        CardLayout layout = (CardLayout) loginJPanel.getLayout();
        layout.next(loginJPanel);
    }//GEN-LAST:event_deliveryAgentJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        loginJPanel.remove(this);
        CardLayout layout = (CardLayout) loginJPanel.getLayout();
        layout.previous(loginJPanel);        // TODO add your handling code here:
    }//GEN-LAST:event_backJButtonActionPerformed

    private void customerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerJButtonActionPerformed
        RgtCJPanel rcj = new RgtCJPanel(system, loginJPanel);
        loginJPanel.add(rcj);
        CardLayout layout = (CardLayout) loginJPanel.getLayout();
        layout.next(loginJPanel);
    }//GEN-LAST:event_customerJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton customerJButton;
    private javax.swing.JButton deliveryAgentJButton;
    private javax.swing.JButton storeJButton;
    // End of variables declaration//GEN-END:variables
}
