/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Business.Business.EcoSystem;
import Business.Business.Person;
import Business.Customer.Customer;
import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.CustomerCenter;
import Business.Enterprise.Enterprise;
import Business.Organization.CustomerOrganization;
import Business.Organization.Organization;

import Business.Role.CustomerRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author tzm
 */
public class RgtCJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RgtCJPanel
     */
    private EcoSystem system;
    private JPanel loginJPanel;

  

    /**
     * Creates new form LoginJPanel
     */
    public RgtCJPanel(EcoSystem system, JPanel loginJPanel) {
        initComponents();
        this.system = system;
        this.loginJPanel = loginJPanel;
       
        this.setSize(300, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        registerJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        passwordJPasswordField = new javax.swing.JPasswordField();
        PhoneTextField = new javax.swing.JTextField();
        storeNamejLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        addressjLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        addressTextArea = new javax.swing.JTextArea();
        storeNamejLabel1 = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();

        backJButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        backJButton.setText("Back");
        backJButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        backJButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel8.setText("UserName:");

        userNameTextField.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel9.setText("Password:");

        registerJButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        registerJButton.setText("Register");
        registerJButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        registerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerJButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel2.setText("PhoneNumber:");

        passwordJPasswordField.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N

        PhoneTextField.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N

        storeNamejLabel.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        storeNamejLabel.setText("FirstName:");

        firstNameTextField.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N

        addressjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        addressjLabel.setText("Address: ");

        addressTextArea.setColumns(20);
        addressTextArea.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jScrollPane4.setViewportView(addressTextArea);

        storeNamejLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        storeNamejLabel1.setText("LastName:");

        lastNameTextField.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(storeNamejLabel1)
                            .addComponent(storeNamejLabel)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(PhoneTextField)
                            .addComponent(jScrollPane4)
                            .addComponent(userNameTextField)
                            .addComponent(passwordJPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(addressjLabel)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(lastNameTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(registerJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(storeNamejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(storeNamejLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addressjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordJPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerJButton)
                .addContainerGap(75, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        loginJPanel.remove(this);
        CardLayout layout = (CardLayout) loginJPanel.getLayout();
        layout.previous(loginJPanel);        // TODO add your handling code here:
    }//GEN-LAST:event_backJButtonActionPerformed

    private void registerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerJButtonActionPerformed
        String firstName = firstNameTextField.getText();
        String lastName = lastNameTextField.getText();
        String address = addressTextArea.getText();
        String phone = PhoneTextField.getText();
        String userName = userNameTextField.getText();
        String password = String.valueOf(passwordJPasswordField.getPassword());

        if (firstName.trim().equals("") || lastName.trim().equals("") ||address.trim().equals("") || phone.trim().equals("") || userName.trim().equals("") || password.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Input cannot be empty!");
            return;
        }
        try{
         long l= Long.parseLong(phone);
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Incorrect phone number input format!");
            return;
        }
        Boolean used = false;

        for (UserAccount ua : system.getUserAccountDirectory().getUserAccountList()) {
            if (userName.equals(ua.getUsername())) {

                used = true;
                break;
            }

        }

        if (used == false) {
            Label1:
            for (Enterprise en : system.getEnterpriseDirectory().getEnterpriseList()) {

                for (Organization org : en.getOrganizationDirectory().getOrganizationList()) {
                    for (UserAccount ua : org.getUserAccountDirectory().getUserAccountList()) {
                        if (userName.equals(ua.getUsername())) {

                            used = true;
                            break Label1;

                        }

                    }
                }

            }
        }
        if (used == true) {

            JOptionPane.showMessageDialog(this, "UserName has been used", "Warning", JOptionPane.WARNING_MESSAGE);
            return;

        }
        
       Customer ct = new Customer();
       ct.setFirstName(firstName);
       ct.setLastName(lastName);
       ct.setAddress(address);
       ct.setPhone(phone);
         for (Enterprise en : system.getEnterpriseDirectory().getEnterpriseList()) {
            if (en instanceof CustomerCenter) {
                for (Organization org : en.getOrganizationDirectory().getOrganizationList()) {
                     if (org instanceof CustomerOrganization){
                         org.getUserAccountDirectory().createUserAccount(userName, password, ct, new CustomerRole());
                     }
                }
            }
        }
       
       

       
        JOptionPane.showMessageDialog(this, "Registered successfully!", "Information", JOptionPane.DEFAULT_OPTION);
        firstNameTextField.setText("");
        lastNameTextField.setText("");
        addressTextArea.setText("");
        PhoneTextField.setText("");
        userNameTextField.setText("");
        passwordJPasswordField.setText("");
        DB4OUtil.getInstance().storeSystem(system);
    }//GEN-LAST:event_registerJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PhoneTextField;
    private javax.swing.JTextArea addressTextArea;
    private javax.swing.JLabel addressjLabel;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JPasswordField passwordJPasswordField;
    private javax.swing.JButton registerJButton;
    private javax.swing.JLabel storeNamejLabel;
    private javax.swing.JLabel storeNamejLabel1;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
}
