/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import MODEL.Person;
import javax.swing.JOptionPane;

/**
 *
 * @author 加藤鹰
 */
public class DemographicInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DemographicInfoJPanel
     */
    Person person;
    public DemographicInfoJPanel(Person person) {
        initComponents();
        this.person =person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DemoInfojLabel = new javax.swing.JLabel();
        NamejLabel2 = new javax.swing.JLabel();
        PhoneNumberjLabel3 = new javax.swing.JLabel();
        DobjLabel4 = new javax.swing.JLabel();
        AgejLabel5 = new javax.swing.JLabel();
        HeightjLabel6 = new javax.swing.JLabel();
        WeightjLabel7 = new javax.swing.JLabel();
        SocialNumberjLabel8 = new javax.swing.JLabel();
        NamejTextField2 = new javax.swing.JTextField();
        PhoneNumberjTextField3 = new javax.swing.JTextField();
        DOBjTextField4 = new javax.swing.JTextField();
        AgejTextField6 = new javax.swing.JTextField();
        HeightjTextField5 = new javax.swing.JTextField();
        WeightjTextField7 = new javax.swing.JTextField();
        SocialNumberjTextField8 = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(204, 255, 204));

        DemoInfojLabel.setBackground(new java.awt.Color(204, 255, 204));
        DemoInfojLabel.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        DemoInfojLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DemoInfojLabel.setText("Demographic info");
        DemoInfojLabel.setToolTipText("");

        NamejLabel2.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        NamejLabel2.setText("Name");

        PhoneNumberjLabel3.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        PhoneNumberjLabel3.setText("PhoneNumber");

        DobjLabel4.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        DobjLabel4.setText("DOB");

        AgejLabel5.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        AgejLabel5.setText("Age");

        HeightjLabel6.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        HeightjLabel6.setText("Heiget");

        WeightjLabel7.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        WeightjLabel7.setText("Weight");

        SocialNumberjLabel8.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        SocialNumberjLabel8.setText("SocialSecurityNumber");

        NamejTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamejTextField2ActionPerformed(evt);
            }
        });

        SocialNumberjTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SocialNumberjTextField8ActionPerformed(evt);
            }
        });

        btnSave.setText("create");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DemoInfojLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NamejLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(NamejTextField2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PhoneNumberjLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(PhoneNumberjTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DobjLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(DOBjTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(HeightjLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(HeightjTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AgejLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(AgejTextField6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(WeightjLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(WeightjTextField7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SocialNumberjLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(SocialNumberjTextField8))))
                .addGap(10, 10, 10))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AgejLabel5, DobjLabel4, HeightjLabel6, NamejLabel2, PhoneNumberjLabel3, SocialNumberjLabel8, WeightjLabel7});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(DemoInfojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamejLabel2)
                    .addComponent(NamejTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNumberjLabel3)
                    .addComponent(PhoneNumberjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DobjLabel4)
                    .addComponent(DOBjTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgejLabel5)
                    .addComponent(AgejTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HeightjLabel6)
                    .addComponent(HeightjTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WeightjLabel7)
                    .addComponent(WeightjTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SocialNumberjLabel8)
                    .addComponent(SocialNumberjTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {DobjLabel4, HeightjLabel6, NamejLabel2, PhoneNumberjLabel3, SocialNumberjLabel8, WeightjLabel7});

    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        person.setName(NamejTextField2.getText());
        person.setPhoneNumber(PhoneNumberjTextField3.getText());
        person.setDateOfBirth(DOBjTextField4.getText());
        person.setAge(AgejTextField6.getText());
        person.setHeight(HeightjTextField5.getText());
        person.setWeight(WeightjTextField7.getText());
        person.setSocialSecurityNumber(SocialNumberjTextField8.getText());
        JOptionPane.showMessageDialog(this, "person information saved");
     
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void SocialNumberjTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SocialNumberjTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SocialNumberjTextField8ActionPerformed

    private void NamejTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamejTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamejTextField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgejLabel5;
    private javax.swing.JTextField AgejTextField6;
    private javax.swing.JTextField DOBjTextField4;
    private javax.swing.JLabel DemoInfojLabel;
    private javax.swing.JLabel DobjLabel4;
    private javax.swing.JLabel HeightjLabel6;
    private javax.swing.JTextField HeightjTextField5;
    private javax.swing.JLabel NamejLabel2;
    private javax.swing.JTextField NamejTextField2;
    private javax.swing.JLabel PhoneNumberjLabel3;
    private javax.swing.JTextField PhoneNumberjTextField3;
    private javax.swing.JLabel SocialNumberjLabel8;
    private javax.swing.JTextField SocialNumberjTextField8;
    private javax.swing.JLabel WeightjLabel7;
    private javax.swing.JTextField WeightjTextField7;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
