/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import MODEL.Person;

/**
 *
 * @author 加藤鹰
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    Person person;
    public JFrame() {
        initComponents();
        person = new Person();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        ControlPanel = new javax.swing.JPanel();
        btnDemoInfo = new javax.swing.JButton();
        btnAddInfo = new javax.swing.JButton();
        btnSaveInfo = new javax.swing.JButton();
        btnCheckInfo = new javax.swing.JButton();
        btnDriverInfo = new javax.swing.JButton();
        btnMedical = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        WorkArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane.setPreferredSize(new java.awt.Dimension(550, 400));

        ControlPanel.setBackground(new java.awt.Color(153, 153, 153));
        ControlPanel.setForeground(new java.awt.Color(51, 51, 255));

        btnDemoInfo.setText("Demographic info");
        btnDemoInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDemoInfoActionPerformed(evt);
            }
        });

        btnAddInfo.setText("Address information");
        btnAddInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddInfoActionPerformed(evt);
            }
        });

        btnSaveInfo.setText("Saving account information");
        btnSaveInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveInfoActionPerformed(evt);
            }
        });

        btnCheckInfo.setText("Checking account information");
        btnCheckInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInfoActionPerformed(evt);
            }
        });

        btnDriverInfo.setText("Driver’s license information");
        btnDriverInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDriverInfoActionPerformed(evt);
            }
        });

        btnMedical.setText("Medical Record");
        btnMedical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicalActionPerformed(evt);
            }
        });

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ControlPanelLayout = new javax.swing.GroupLayout(ControlPanel);
        ControlPanel.setLayout(ControlPanelLayout);
        ControlPanelLayout.setHorizontalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCheckInfo)
                    .addComponent(btnSaveInfo)
                    .addComponent(btnAddInfo)
                    .addComponent(btnDemoInfo)
                    .addComponent(btnDriverInfo)
                    .addComponent(btnMedical)
                    .addComponent(btnPrint))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ControlPanelLayout.setVerticalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDemoInfo)
                .addGap(18, 18, 18)
                .addComponent(btnAddInfo)
                .addGap(18, 18, 18)
                .addComponent(btnSaveInfo)
                .addGap(18, 18, 18)
                .addComponent(btnCheckInfo)
                .addGap(18, 18, 18)
                .addComponent(btnDriverInfo)
                .addGap(18, 18, 18)
                .addComponent(btnMedical)
                .addGap(18, 18, 18)
                .addComponent(btnPrint)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        jSplitPane.setLeftComponent(ControlPanel);

        WorkArea.setBackground(new java.awt.Color(153, 0, 255));
        WorkArea.setPreferredSize(new java.awt.Dimension(450, 3400));

        javax.swing.GroupLayout WorkAreaLayout = new javax.swing.GroupLayout(WorkArea);
        WorkArea.setLayout(WorkAreaLayout);
        WorkAreaLayout.setHorizontalGroup(
            WorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );
        WorkAreaLayout.setVerticalGroup(
            WorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        jSplitPane.setRightComponent(WorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDemoInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDemoInfoActionPerformed
        // TODO add your handling code here:
        DemographicInfoJPanel demopanel= new DemographicInfoJPanel(person);
        jSplitPane.setRightComponent(demopanel);
    }//GEN-LAST:event_btnDemoInfoActionPerformed

    private void btnAddInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddInfoActionPerformed
        // TODO add your handling code here:
         AddInfoJPanel addinfopanel= new AddInfoJPanel(person);
        jSplitPane.setRightComponent(addinfopanel);
    }//GEN-LAST:event_btnAddInfoActionPerformed

    private void btnSaveInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveInfoActionPerformed
        // TODO add your handling code here:
        SavingAccountInfoJPanel savingaccountinfoJPanel= new SavingAccountInfoJPanel(person);
        jSplitPane.setRightComponent(savingaccountinfoJPanel);
    }//GEN-LAST:event_btnSaveInfoActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        PrintViewJPanel  printviewjpanel = new PrintViewJPanel(person);
        jSplitPane.setRightComponent(printviewjpanel);
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnCheckInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInfoActionPerformed
        // TODO add your handling code here:
         CheckingAccountInfoJPanel checkingaccountjpanel =new CheckingAccountInfoJPanel(person);
          jSplitPane.setRightComponent(checkingaccountjpanel);
         
    }//GEN-LAST:event_btnCheckInfoActionPerformed

    private void btnDriverInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDriverInfoActionPerformed
        // TODO add your handling code here:
        DriverlicenseInfoJPanel driverlicenseinforjpanel = new DriverlicenseInfoJPanel(person);
        jSplitPane.setRightComponent(driverlicenseinforjpanel);
    }//GEN-LAST:event_btnDriverInfoActionPerformed

    private void btnMedicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicalActionPerformed
        // TODO add your handling code here:
        MedicalRecordJPanel licenseinforjpanel = new MedicalRecordJPanel(person);
        jSplitPane.setRightComponent(licenseinforjpanel);
    }//GEN-LAST:event_btnMedicalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JPanel WorkArea;
    private javax.swing.JButton btnAddInfo;
    private javax.swing.JButton btnCheckInfo;
    private javax.swing.JButton btnDemoInfo;
    private javax.swing.JButton btnDriverInfo;
    private javax.swing.JButton btnMedical;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSaveInfo;
    private javax.swing.JSplitPane jSplitPane;
    // End of variables declaration//GEN-END:variables
}
