/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import MODEL.Person;
import javax.swing.JOptionPane;

/**
 *
 * @author 加藤鹰
 */
public class AddInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddInfoJPanel
     */
    Person person;
    public AddInfoJPanel(Person person) {
        initComponents();
        this.person=person; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        streetaddressjLabel2 = new javax.swing.JLabel();
        addressinformationjLabel = new javax.swing.JLabel();
        statejLabel3 = new javax.swing.JLabel();
        zipcodejLabel4 = new javax.swing.JLabel();
        cityjLabel5 = new javax.swing.JLabel();
        citystatejTextField3 = new javax.swing.JTextField();
        zipcodejTextField4 = new javax.swing.JTextField();
        cityjTextField6 = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        streetaddressjTextField4 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 204));

        streetaddressjLabel2.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        streetaddressjLabel2.setText("StreetAddress");

        addressinformationjLabel.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        addressinformationjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addressinformationjLabel.setText("Address information");
        addressinformationjLabel.setToolTipText("");

        statejLabel3.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        statejLabel3.setText("State");

        zipcodejLabel4.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        zipcodejLabel4.setText("ZipCode");

        cityjLabel5.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        cityjLabel5.setText("City");

        btnSave.setText("create");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addressinformationjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statejLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(streetaddressjLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(zipcodejLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(119, 119, 119))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cityjLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cityjTextField6)
                            .addComponent(zipcodejTextField4)
                            .addComponent(citystatejTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(streetaddressjTextField4))
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(addressinformationjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(streetaddressjLabel2)
                    .addComponent(streetaddressjTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statejLabel3)
                    .addComponent(citystatejTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zipcodejLabel4)
                    .addComponent(zipcodejTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityjLabel5)
                    .addComponent(cityjTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(123, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        person.setStreetAddress(streetaddressjTextField4.getText());
        person.setCityState(citystatejTextField3.getText());
        person.setZipCode(zipcodejTextField4.getText());
        person.setState(cityjTextField6.getText());
        JOptionPane.showMessageDialog(this, "person information saved");
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressinformationjLabel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel cityjLabel5;
    private javax.swing.JTextField cityjTextField6;
    private javax.swing.JTextField citystatejTextField3;
    private javax.swing.JLabel statejLabel3;
    private javax.swing.JLabel streetaddressjLabel2;
    private javax.swing.JTextField streetaddressjTextField4;
    private javax.swing.JLabel zipcodejLabel4;
    private javax.swing.JTextField zipcodejTextField4;
    // End of variables declaration//GEN-END:variables
}
